const MAX_TITLE_LENGTH = 125;
const MAX_DESCRIPTION_LENGTH = 1000;
const PAGE_SIZE = 10;
const DEFAULT_PAGE_NUMBER = 1;

export {
  MAX_DESCRIPTION_LENGTH,
  MAX_TITLE_LENGTH,
  PAGE_SIZE,
  DEFAULT_PAGE_NUMBER,
};
